### PR TITLE
performance tweaks

### PR DESCRIPTION
**Pull request by al12gamer**
added fsync kernel and mesa-aco options to the full install
changed upgrade options based on recommendations from gloriouseggroll
More info on fsync kernel here: https://copr.fedorainfracloud.org/coprs/sentry/kernel-fsync/
mesa-aco: https://copr.fedorainfracloud.org/coprs/gloriouseggroll/mesa-aco/

### CODE REVIEW

**Comment by TechnologyMan101** [comment]
Looks good so far! I'll go ahead and merge this after testing on my laptop (around 30 minutes). I might add this to the minimal install (and private scripts), too, if it's a significant enough improvement

**Comment by TechnologyMan101** [comment]
Also, I'll probably integrate this by editing the local files on the computer, so it'll be manually merged
I have a couple things to fix in the script anyway, so it fits perfectly into my timeline

**Comment by TechnologyMan101** [comment]
Merged with tiny changes (`-y`), also included in minimal install

**Comment by al12gamer** [comment]
I take it you just added the lines to the full install? Let me know how mesa is.

**Comment by TechnologyMan101** [comment]
Yep, I didn't merge it directly from here because I already had a some stuff I needed to add
I'm not sure what I would need to test Mesa on though
But I'm finished with my other work, so I have time
I'm in a place with excellent signal right now (177 mbps/40 mbps) so I can easily test stuff

**Comment by al12gamer** [comment]
best tests for mesa-aco additions would be anything requiring intel iGPU or amd iGPU/dGPU

**Comment by TechnologyMan101** [comment]
I'll go ahead and test it on Minecraft or something (really the only intensive thing I have other than VMs)
It'll be a bit as I noticed some kernel updates I need to do
I'm also supplying internet to the family over this computer so I can't reboot for a while

**Comment by TechnologyMan101** [comment]
Tested and framerate definitely seems more stable

**Pull request closed without merging**
